#!/bin/bash
# Combine osgNativeLib with OpenSceneGraph static libraries
# into single library for convenience.
OSG_NATIVE_LIB_BUILD_DIR=$1
OSG_BUILD_DIR=$2

OUTPUT_LIB=libosglib.a
OSG_NATIVE_LIB=libosgNativeLib.a
OSG_NATIVE_LIB_INTERNAL_DIR=Release-iphonesimulator

echo "Creating single static osglib \"$OUTPUT_DIR/$OUTPUT_LIB\""

libtool -static -o $OSG_NATIVE_LIB_BUILD_DIR/$OUTPUT_LIB \
    $OSG_NATIVE_LIB_BUILD_DIR/$OSG_NATIVE_LIB_INTERNAL_DIR/$OSG_NATIVE_LIB \
    $OSG_BUILD_DIR/lib/libOpenThreads.a \
    $OSG_BUILD_DIR/lib/libosg.a \
    $OSG_BUILD_DIR/lib/libosgDB.a \
    $OSG_BUILD_DIR/lib/libosgdb_osg.a \
    $OSG_BUILD_DIR/lib/libosgdb_serializers_osg.a \
    $OSG_BUILD_DIR/lib/libosgGA.a \
    $OSG_BUILD_DIR/lib/libosgShadow.a \
    $OSG_BUILD_DIR/lib/libosgText.a \
    $OSG_BUILD_DIR/lib/libosgUtil.a \
    $OSG_BUILD_DIR/lib/libosgViewer.a
