#!/bin/bash
# Create universal (fat, multi-architecture) OpenSceneGraph libraries
# for inclusion under iOS.

BUILD_DIR=$1

if [ -z "$BUILD_DIR" ]; then
    echo "Usage: $0 /path/to/build/dir/OpenSceneGraph-for-iOS"
    exit 1
fi

UNIVERSAL_LIB_DIR=$BUILD_DIR/universal_lib
mkdir -p $UNIVERSAL_LIB_DIR
echo "Created universal library directory: '$UNIVERSAL_LIB_DIR'"

LIBS="osgViewer
osgDB
osgdb_osg
osgdb_serializers_osg
osgGA
osgShadow
osgText
osgUtil
OpenThreads"
for lib in $LIBS; do
    libName="lib${lib}.a"
    lipo -output $UNIVERSAL_LIB_DIR/$libName -create $BUILD_DIR/lib/$libName
    echo "Created library: '$UNIVERSAL_LIB_DIR/$libName'"
done

